### ISSUE TITLE
error with WooCommerce 4 and Tribe Events Tickets 4.11.4

### ISSUE THREAD

**Issue by slightlydiff** [mt-support/tribe-ext-woo-order-templates#2]
When installed with WooCommerce 4 and Tribe Events Tickets 4.11.4 I get:

`Uncaught Error: Class 'Tribe\\Extensions\\ET_Woo_Order_Details\\Main' not found in /home/webeasy/webapps/webeasy/wp-content/plugins/tribe-ext-woo-order-templates/Bootstrap.php:87\nStack trace:\n`

**Comment by cliffordp** [comment]
Hi. We don't provide support here, only at https://support.theeventscalendar.com/
