### ISSUE TITLE
Checkboxes not coming through

### ISSUE THREAD

**Issue by edrussell** [mt-support/tribe-ext-woo-order-templates#3]
Hi,

WooCommerce  3.9.1
Event Tickets Plus 4.11.2

Checkboxes are no longer pulling through into the description.  I've dumped the post meta and can see the values but they aren't coming though this extension. 

Please help!  Thanks in advance!

Ed.

**Comment by cliffordp** [comment]
Hi. We don't provide support here, only at https://support.theeventscalendar.com/
